### ISSUE TITLE
Road Map - ToDo

### ISSUE THREAD

**Issue by KeithSloan** [KeithSloan/GDML#85]
- [ ] continue implementing arrays: along path, points, circular

- [ ] extrude remaining types of curves: parabola, hyperbola, other kind of spline

- [ ] extrude self crossing edges

- [ ] implement reading of gdml elements: replicas, loops, parametrized solids

- [ ] icons/commands for constructing remaining types of gdml solids

- [ ] Add support for Parameterised Volumes see GDML manual section 3.5.3

- [ ] Add support for import Gmsh.MSH file

**Comment by luzpaz** [comment]
- [ ] Consider using checkboxes?
